// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syncdirectory.proto

/*
Package syncdirectory is a generated protocol buffer package.

It is generated from these files:
	syncdirectory.proto

It has these top-level messages:
	MInitDirectory
	MPushDirectory
	MPullDirectory
	MSyncDirectory
	MPushFile
	MPullFile
	MDeleteFile
	MMoveFile
*/
package syncdirectory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ESyncMsgCode int32

const (
	ESyncMsgCode_EInitDirectory ESyncMsgCode = 0
	ESyncMsgCode_EPushDirectory ESyncMsgCode = 1
	ESyncMsgCode_EPullDirectory ESyncMsgCode = 2
	ESyncMsgCode_ESyncDirectory ESyncMsgCode = 3
	ESyncMsgCode_EPushFile      ESyncMsgCode = 4
	ESyncMsgCode_EPullFile      ESyncMsgCode = 5
	ESyncMsgCode_EDeleteFile    ESyncMsgCode = 6
	ESyncMsgCode_EMoveFile      ESyncMsgCode = 7
)

var ESyncMsgCode_name = map[int32]string{
	0: "EInitDirectory",
	1: "EPushDirectory",
	2: "EPullDirectory",
	3: "ESyncDirectory",
	4: "EPushFile",
	5: "EPullFile",
	6: "EDeleteFile",
	7: "EMoveFile",
}
var ESyncMsgCode_value = map[string]int32{
	"EInitDirectory": 0,
	"EPushDirectory": 1,
	"EPullDirectory": 2,
	"ESyncDirectory": 3,
	"EPushFile":      4,
	"EPullFile":      5,
	"EDeleteFile":    6,
	"EMoveFile":      7,
}

func (x ESyncMsgCode) Enum() *ESyncMsgCode {
	p := new(ESyncMsgCode)
	*p = x
	return p
}
func (x ESyncMsgCode) String() string {
	return proto.EnumName(ESyncMsgCode_name, int32(x))
}
func (x *ESyncMsgCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ESyncMsgCode_value, data, "ESyncMsgCode")
	if err != nil {
		return err
	}
	*x = ESyncMsgCode(value)
	return nil
}
func (ESyncMsgCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MInitDirectory struct {
	Root             *string `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MInitDirectory) Reset()                    { *m = MInitDirectory{} }
func (m *MInitDirectory) String() string            { return proto.CompactTextString(m) }
func (*MInitDirectory) ProtoMessage()               {}
func (*MInitDirectory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MInitDirectory) GetRoot() string {
	if m != nil && m.Root != nil {
		return *m.Root
	}
	return ""
}

type MPushDirectory struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MPushDirectory) Reset()                    { *m = MPushDirectory{} }
func (m *MPushDirectory) String() string            { return proto.CompactTextString(m) }
func (*MPushDirectory) ProtoMessage()               {}
func (*MPushDirectory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MPullDirectory struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MPullDirectory) Reset()                    { *m = MPullDirectory{} }
func (m *MPullDirectory) String() string            { return proto.CompactTextString(m) }
func (*MPullDirectory) ProtoMessage()               {}
func (*MPullDirectory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MSyncDirectory struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MSyncDirectory) Reset()                    { *m = MSyncDirectory{} }
func (m *MSyncDirectory) String() string            { return proto.CompactTextString(m) }
func (*MSyncDirectory) ProtoMessage()               {}
func (*MSyncDirectory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type MPushFile struct {
	Root             *string `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	FileName         *string `protobuf:"bytes,2,opt,name=fileName" json:"fileName,omitempty"`
	FileSize         *int32  `protobuf:"varint,3,opt,name=fileSize" json:"fileSize,omitempty"`
	FileDir          *string `protobuf:"bytes,4,opt,name=fileDir" json:"fileDir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MPushFile) Reset()                    { *m = MPushFile{} }
func (m *MPushFile) String() string            { return proto.CompactTextString(m) }
func (*MPushFile) ProtoMessage()               {}
func (*MPushFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MPushFile) GetRoot() string {
	if m != nil && m.Root != nil {
		return *m.Root
	}
	return ""
}

func (m *MPushFile) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *MPushFile) GetFileSize() int32 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *MPushFile) GetFileDir() string {
	if m != nil && m.FileDir != nil {
		return *m.FileDir
	}
	return ""
}

type MPullFile struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MPullFile) Reset()                    { *m = MPullFile{} }
func (m *MPullFile) String() string            { return proto.CompactTextString(m) }
func (*MPullFile) ProtoMessage()               {}
func (*MPullFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type MDeleteFile struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MDeleteFile) Reset()                    { *m = MDeleteFile{} }
func (m *MDeleteFile) String() string            { return proto.CompactTextString(m) }
func (*MDeleteFile) ProtoMessage()               {}
func (*MDeleteFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type MMoveFile struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MMoveFile) Reset()                    { *m = MMoveFile{} }
func (m *MMoveFile) String() string            { return proto.CompactTextString(m) }
func (*MMoveFile) ProtoMessage()               {}
func (*MMoveFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*MInitDirectory)(nil), "syncdirectory.MInitDirectory")
	proto.RegisterType((*MPushDirectory)(nil), "syncdirectory.MPushDirectory")
	proto.RegisterType((*MPullDirectory)(nil), "syncdirectory.MPullDirectory")
	proto.RegisterType((*MSyncDirectory)(nil), "syncdirectory.MSyncDirectory")
	proto.RegisterType((*MPushFile)(nil), "syncdirectory.MPushFile")
	proto.RegisterType((*MPullFile)(nil), "syncdirectory.MPullFile")
	proto.RegisterType((*MDeleteFile)(nil), "syncdirectory.MDeleteFile")
	proto.RegisterType((*MMoveFile)(nil), "syncdirectory.MMoveFile")
	proto.RegisterEnum("syncdirectory.ESyncMsgCode", ESyncMsgCode_name, ESyncMsgCode_value)
}

func init() { proto.RegisterFile("syncdirectory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x7f, 0x28, 0x99, 0x90, 0x30, 0x32, 0x1b, 0x8b, 0x55, 0x15, 0xb1, 0xa8, 0x58,
	0x70, 0x09, 0x12, 0x24, 0x16, 0x46, 0xa8, 0x3d, 0x01, 0x4a, 0x0d, 0x58, 0x32, 0x31, 0x38, 0x06,
	0x29, 0x9c, 0x85, 0xc3, 0x22, 0x0f, 0x71, 0x8a, 0x25, 0x76, 0xf3, 0xbe, 0x97, 0xc9, 0xbc, 0x67,
	0x38, 0xef, 0x87, 0xae, 0xdd, 0x6b, 0xa7, 0x5a, 0x6f, 0xdd, 0x70, 0xfd, 0xe6, 0xac, 0xb7, 0xbc,
	0x48, 0x60, 0x75, 0x09, 0xa5, 0xbc, 0xeb, 0xb4, 0xaf, 0x23, 0xe1, 0x1c, 0x16, 0xce, 0x5a, 0x2f,
	0xd8, 0x9a, 0x6d, 0xb2, 0x2d, 0xcd, 0x15, 0x42, 0x29, 0x1f, 0x3e, 0xfa, 0x97, 0xe9, 0xab, 0x91,
	0x18, 0x93, 0x92, 0xdd, 0xd0, 0xb5, 0x07, 0xf2, 0x0e, 0x19, 0x6d, 0xdd, 0x6a, 0xa3, 0xfe, 0xfb,
	0x2d, 0xbf, 0x80, 0x93, 0x27, 0x6d, 0xd4, 0xfd, 0xe3, 0xab, 0x12, 0x33, 0xe2, 0x93, 0x8e, 0xde,
	0x4e, 0x7f, 0x29, 0x31, 0x5f, 0xb3, 0xcd, 0x72, 0x3b, 0x69, 0x2e, 0x60, 0x15, 0xe6, 0x5a, 0x3b,
	0xb1, 0xa0, 0xb5, 0x28, 0xab, 0x9c, 0x4e, 0x1a, 0x13, 0x4e, 0x56, 0x05, 0xe4, 0xb2, 0x56, 0x46,
	0x79, 0x45, 0x32, 0x78, 0xd2, 0x7e, 0x92, 0xb8, 0xfa, 0x66, 0x70, 0xda, 0x84, 0xb8, 0xb2, 0x7f,
	0xbe, 0xb1, 0xfb, 0x90, 0xaf, 0x6c, 0x92, 0x87, 0xc0, 0x23, 0x62, 0x49, 0x6d, 0x64, 0x23, 0xfb,
	0x53, 0x1c, 0x67, 0xc4, 0x92, 0xea, 0x38, 0xe7, 0x05, 0x64, 0x4d, 0x2c, 0x8f, 0x8b, 0x51, 0xfe,
	0x06, 0xc3, 0x25, 0x3f, 0x83, 0xbc, 0x39, 0x44, 0xc3, 0x63, 0xf2, 0x63, 0x38, 0x5c, 0xfd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0x87, 0x5c, 0xbb, 0xbb, 0x01, 0x00, 0x00,
}
